name: Test Push to GHCR
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: pwd && tree
        run: |          
          tree
          pwd
      - name: Build image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/abcsxl:test .
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}  # 使用内置 token
      - name: Push
        run: docker push ghcr.io/${{ github.repository_owner }}/abcsxl:test
